"""Initial migration

Revision ID: f07fd465ea5b
Revises: 
Create Date: 2026-09-05 17:01:33.550820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07fd465ea5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('org_type', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('slogan', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk_orgdepartment_department'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_department_org_name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_org_id'), ['org_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('audience_type', sa.String(length=50), nullable=True),
    sa.Column('audience_filters', sa.Text(), nullable=True),
    sa.Column('delivery_channels', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('system_event_key', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk_event_org'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_event_active', ['is_active'], unique=False)
        batch_op.create_index('idx_event_org', ['org_id'], unique=False)
        batch_op.create_index('idx_event_system_key', ['system_event_key'], unique=False)
        batch_op.create_index('idx_event_trigger', ['trigger_type'], unique=False)

    op.create_table('org_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk_org_orginvite'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('org_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('comm_type', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('default_view', sa.String(length=50), nullable=True),
    sa.Column('checkin_frequency', sa.String(length=50), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('allow_self_join', sa.Boolean(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk__org_orgsettings'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('remembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('remember_type', sa.String(length=50), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('message_frequency', sa.String(length=20), nullable=True),
    sa.Column('receive_notifications', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk_user_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'org_id', name='uq_user_email_org')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_dob', ['date_of_birth'], unique=False)
        batch_op.create_index('idx_user_joined_date', ['joined_date'], unique=False)
        batch_op.create_index('idx_user_org', ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_emailverification_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('remember_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('\n            (event_id IS NOT NULL AND remember_id IS NULL)\n            OR\n            (event_id IS NULL AND remember_id IS NOT NULL)\n            ', name='ck_template_one_source'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_mestemplate_event'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk_mestemplate_org'),
    sa.ForeignKeyConstraint(['remember_id'], ['remembers.id'], name='fk_mestemplate_remember'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'channel', name='uq_event_template_channel'),
    sa.UniqueConstraint('remember_id', 'channel', name='uq_remember_template_channel')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('related_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('context', sa.String(length=30), nullable=False),
    sa.Column('remember_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk_notification_org'),
    sa.ForeignKeyConstraint(['remember_id'], ['remembers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notification_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_remember_id'), ['remember_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=255), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('depends_on_question_id', sa.Integer(), nullable=True),
    sa.Column('depends_on_value', sa.String(length=100), nullable=True),
    sa.Column('question_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_question_id'], ['questions.id'], name='fk_question_depends'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_question_event'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk_question_org'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_userdepartment_department'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_userdepartment_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', name='uq_user_department')
    )
    op.create_table('user_remembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('remember_type', sa.String(length=50), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_userremember_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('preferred_channel', sa.String(length=50), nullable=True),
    sa.Column('receive_faith_messages', sa.Boolean(), nullable=False),
    sa.Column('tone_preference', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_usersettings'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('remember_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('\n            (event_id IS NOT NULL AND remember_id IS NULL)\n            OR\n            (event_id IS NULL AND remember_id IS NOT NULL)\n            ', name='ck_log_one_source'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_meslog_event'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='fk_meslog_org'),
    sa.ForeignKeyConstraint(['remember_id'], ['remembers.id'], name='fk_meslog_remember'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], name='fk_meslog_template'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_meslog_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', 'occurrence_date', 'channel', name='uq_event_message_occurrence'),
    sa.UniqueConstraint('user_id', 'remember_id', 'occurrence_date', 'channel', name='uq_remember_message_occurrence')
    )
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.create_index('idx_message_event', ['event_id'], unique=False)
        batch_op.create_index('idx_message_remember', ['remember_id'], unique=False)
        batch_op.create_index('idx_message_user', ['user_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='fk_option_question'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('submitted_for_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_response_event'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='fk_response_question'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_response_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', 'question_id', 'submitted_for_date', name='uq_daily_response')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('question_options')
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_message_user')
        batch_op.drop_index('idx_message_remember')
        batch_op.drop_index('idx_message_event')

    op.drop_table('message_logs')
    op.drop_table('user_settings')
    op.drop_table('user_remembers')
    op.drop_table('user_departments')
    op.drop_table('questions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_remember_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_org_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_event_id'))
        batch_op.drop_index('idx_notification_user_read')
        batch_op.drop_index('idx_notification_user_created')

    op.drop_table('notifications')
    op.drop_table('message_templates')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_org')
        batch_op.drop_index('idx_user_joined_date')
        batch_op.drop_index('idx_user_dob')

    op.drop_table('users')
    op.drop_table('remembers')
    op.drop_table('org_settings')
    op.drop_table('org_invites')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_event_trigger')
        batch_op.drop_index('idx_event_system_key')
        batch_op.drop_index('idx_event_org')
        batch_op.drop_index('idx_event_active')

    op.drop_table('events')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_org_id'))

    op.drop_table('departments')
    op.drop_table('organizations')
    # ### end Alembic commands ###
